name: "model-805d47a6-4015-434d-a4b6-bdaadb53c132-backward"
backend: "python"

input [
  {
    name: "INPUT0"
    data_type: TYPE_STRING
    dims: [ 16 ]
  }
]
input [
  {
    name: "INPUT1"
    data_type: TYPE_STRING
    dims: [ 16 ]
  }
]
input [
  {
    name: "NAME_MAPPING"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [ 46 ]
  }
]
output [
  {
    name: "OUTPUT1"
    data_type: TYPE_FP64
    dims: [ 46 ]
  }
]

instance_group [
  {
    kind: KIND_CPU
  }
]
