graph:
- metadata:
    data_key: ''
    data_unit: second
    max_historical_periods: 0
    mode: backward
  topo_ids:
  - 7dd2bebb-e9b4-4cbb-bf5c-08dc1b3fa25f
  - bfc468af-65b3-4c79-bf59-08dc1b3fa25f
  - output
  type: normal
nodes:
- id: 7dd2bebb-e9b4-4cbb-bf5c-08dc1b3fa25f
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat12
      mappings:
        feat12: feat12
  outputs:
  - feat12
  parents:
  - input
  transform_class: MinMaxTransform
- id: 7dd2bebb-e9b4-4cbb-bf5c-08dc1b3fa25f
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat12
      mappings:
        feat12: feat12
  outputs:
  - feat12
  parents:
  - input
  transform_class: MinMaxTransform
- id: bfc468af-65b3-4c79-bf59-08dc1b3fa25f
  init_kwargs: {}
  inputs:
    7dd2bebb-e9b4-4cbb-bf5c-08dc1b3fa25f:
      columns:
      - feat12
      mappings:
        feat12: feat12_22
  outputs:
  - feat12_22
  parents:
  - 7dd2bebb-e9b4-4cbb-bf5c-08dc1b3fa25f
  transform_class: TargetPass
- id: bfc468af-65b3-4c79-bf59-08dc1b3fa25f
  init_kwargs: {}
  inputs:
    7dd2bebb-e9b4-4cbb-bf5c-08dc1b3fa25f:
      columns:
      - feat12
      mappings:
        feat12: feat12_22
  outputs:
  - feat12_22
  parents:
  - 7dd2bebb-e9b4-4cbb-bf5c-08dc1b3fa25f
  transform_class: TargetPass
- id: output
  init_kwargs: {}
  inputs:
    17da2638-5f8b-4a6f-bf5a-08dc1b3fa25f:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat1_1
      - feat2_1
      - feat3_1
      - feat4_1
      - feat5_1
      - feat6_1
      - feat7_1
      - feat8_1
      - feat9_1
      - feat10_1
      - feat11_1
      - feat1_2
      - feat2_2
      - feat3_2
      - feat4_2
      - feat5_2
      - feat6_2
      - feat7_2
      - feat8_2
      - feat9_2
      - feat10_2
      - feat11_2
      - feat1_3
      - feat2_3
      - feat3_3
      - feat4_3
      - feat5_3
      - feat6_3
      - feat7_3
      - feat8_3
      - feat9_3
      - feat10_3
      - feat11_3
      mappings:
        feat1: feat1
        feat10: feat10
        feat10_1: feat10_1
        feat10_2: feat10_2
        feat10_3: feat10_3
        feat11: feat11
        feat11_1: feat11_1
        feat11_2: feat11_2
        feat11_3: feat11_3
        feat1_1: feat1_1
        feat1_2: feat1_2
        feat1_3: feat1_3
        feat2: feat2
        feat2_1: feat2_1
        feat2_2: feat2_2
        feat2_3: feat2_3
        feat3: feat3
        feat3_1: feat3_1
        feat3_2: feat3_2
        feat3_3: feat3_3
        feat4: feat4
        feat4_1: feat4_1
        feat4_2: feat4_2
        feat4_3: feat4_3
        feat5: feat5
        feat5_1: feat5_1
        feat5_2: feat5_2
        feat5_3: feat5_3
        feat6: feat6
        feat6_1: feat6_1
        feat6_2: feat6_2
        feat6_3: feat6_3
        feat7: feat7
        feat7_1: feat7_1
        feat7_2: feat7_2
        feat7_3: feat7_3
        feat8: feat8
        feat8_1: feat8_1
        feat8_2: feat8_2
        feat8_3: feat8_3
        feat9: feat9
        feat9_1: feat9_1
        feat9_2: feat9_2
        feat9_3: feat9_3
    bfc468af-65b3-4c79-bf59-08dc1b3fa25f:
      columns:
      - feat12_22
      mappings:
        feat12_22: feat12_22
  outputs:
  - feat12_22
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  parents:
  - bfc468af-65b3-4c79-bf59-08dc1b3fa25f
  - 17da2638-5f8b-4a6f-bf5a-08dc1b3fa25f
  transform_class: DefaultTransformer
- id: output
  init_kwargs: {}
  inputs:
    17da2638-5f8b-4a6f-bf5a-08dc1b3fa25f:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat1_1
      - feat2_1
      - feat3_1
      - feat4_1
      - feat5_1
      - feat6_1
      - feat7_1
      - feat8_1
      - feat9_1
      - feat10_1
      - feat11_1
      - feat1_2
      - feat2_2
      - feat3_2
      - feat4_2
      - feat5_2
      - feat6_2
      - feat7_2
      - feat8_2
      - feat9_2
      - feat10_2
      - feat11_2
      - feat1_3
      - feat2_3
      - feat3_3
      - feat4_3
      - feat5_3
      - feat6_3
      - feat7_3
      - feat8_3
      - feat9_3
      - feat10_3
      - feat11_3
      mappings:
        feat1: feat1
        feat10: feat10
        feat10_1: feat10_1
        feat10_2: feat10_2
        feat10_3: feat10_3
        feat11: feat11
        feat11_1: feat11_1
        feat11_2: feat11_2
        feat11_3: feat11_3
        feat1_1: feat1_1
        feat1_2: feat1_2
        feat1_3: feat1_3
        feat2: feat2
        feat2_1: feat2_1
        feat2_2: feat2_2
        feat2_3: feat2_3
        feat3: feat3
        feat3_1: feat3_1
        feat3_2: feat3_2
        feat3_3: feat3_3
        feat4: feat4
        feat4_1: feat4_1
        feat4_2: feat4_2
        feat4_3: feat4_3
        feat5: feat5
        feat5_1: feat5_1
        feat5_2: feat5_2
        feat5_3: feat5_3
        feat6: feat6
        feat6_1: feat6_1
        feat6_2: feat6_2
        feat6_3: feat6_3
        feat7: feat7
        feat7_1: feat7_1
        feat7_2: feat7_2
        feat7_3: feat7_3
        feat8: feat8
        feat8_1: feat8_1
        feat8_2: feat8_2
        feat8_3: feat8_3
        feat9: feat9
        feat9_1: feat9_1
        feat9_2: feat9_2
        feat9_3: feat9_3
    bfc468af-65b3-4c79-bf59-08dc1b3fa25f:
      columns:
      - feat12_22
      mappings:
        feat12_22: feat12_22
  outputs:
  - feat12_22
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  parents:
  - bfc468af-65b3-4c79-bf59-08dc1b3fa25f
  - 17da2638-5f8b-4a6f-bf5a-08dc1b3fa25f
  transform_class: DefaultTransformer
