graph:
- metadata:
    data_key: ''
    data_unit: second
    max_historical_periods: 3
  mode: forward
  topo_ids:
  - aee696a0-1395-414e-f8c4-08dc15ea238c
  - c4c5cead-63cb-4cd2-f8c9-08dc15ea238c
  - fbb0cc48-4996-4e40-f8c7-08dc15ea238c
  - f0195a31-88d5-4ff8-f8c6-08dc15ea238c
  - e0fe7e13-1286-4df6-f8c5-08dc15ea238c
  - 541db317-589a-44a3-f8c8-08dc15ea238c
  - output
  type: timeseries
nodes:
- id: aee696a0-1395-414e-f8c4-08dc15ea238c
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat12
      mappings:
        feat12: feat12
  outputs:
  - feat12
  parents:
  - input
  transform_class: TargetPass
- id: aee696a0-1395-414e-f8c4-08dc15ea238c
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat12
      mappings:
        feat12: feat12
  outputs:
  - feat12
  parents:
  - input
  transform_class: TargetPass
- id: c4c5cead-63cb-4cd2-f8c9-08dc15ea238c
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      mappings:
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  parents:
  - input
  transform_class: MinMaxTransform
- id: c4c5cead-63cb-4cd2-f8c9-08dc15ea238c
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      mappings:
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  parents:
  - input
  transform_class: MinMaxTransform
- id: fbb0cc48-4996-4e40-f8c7-08dc15ea238c
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat12
      mappings:
        feat12: feat12_22
  outputs:
  - feat12_22
  parents:
  - input
  transform_class: TargetPass
- id: fbb0cc48-4996-4e40-f8c7-08dc15ea238c
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat12
      mappings:
        feat12: feat12_22
  outputs:
  - feat12_22
  parents:
  - input
  transform_class: TargetPass
- id: f0195a31-88d5-4ff8-f8c6-08dc15ea238c
  init_kwargs: {}
  inputs:
    c4c5cead-63cb-4cd2-f8c9-08dc15ea238c:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      mappings:
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  parents:
  - c4c5cead-63cb-4cd2-f8c9-08dc15ea238c
  transform_class: LagFeature
- id: f0195a31-88d5-4ff8-f8c6-08dc15ea238c
  init_kwargs: {}
  inputs:
    c4c5cead-63cb-4cd2-f8c9-08dc15ea238c:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      mappings:
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  parents:
  - c4c5cead-63cb-4cd2-f8c9-08dc15ea238c
  transform_class: LagFeature
- id: e0fe7e13-1286-4df6-f8c5-08dc15ea238c
  init_kwargs: {}
  inputs:
    aee696a0-1395-414e-f8c4-08dc15ea238c:
      columns:
      - feat12
      mappings:
        feat12: feat12_22
    fbb0cc48-4996-4e40-f8c7-08dc15ea238c:
      columns:
      - feat12_22
      mappings:
        feat12_22: feat12_22_22
  outputs:
  - feat12_22_22
  - feat12_22
  parents:
  - fbb0cc48-4996-4e40-f8c7-08dc15ea238c
  - aee696a0-1395-414e-f8c4-08dc15ea238c
  transform_class: TargetPass
- id: e0fe7e13-1286-4df6-f8c5-08dc15ea238c
  init_kwargs: {}
  inputs:
    aee696a0-1395-414e-f8c4-08dc15ea238c:
      columns:
      - feat12
      mappings:
        feat12: feat12_22
    fbb0cc48-4996-4e40-f8c7-08dc15ea238c:
      columns:
      - feat12_22
      mappings:
        feat12_22: feat12_22_22
  outputs:
  - feat12_22_22
  - feat12_22
  parents:
  - fbb0cc48-4996-4e40-f8c7-08dc15ea238c
  - aee696a0-1395-414e-f8c4-08dc15ea238c
  transform_class: TargetPass
- id: 541db317-589a-44a3-f8c8-08dc15ea238c
  init_kwargs: {}
  inputs:
    f0195a31-88d5-4ff8-f8c6-08dc15ea238c:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat1_1
      - feat2_1
      - feat3_1
      - feat4_1
      - feat5_1
      - feat6_1
      - feat7_1
      - feat8_1
      - feat9_1
      - feat10_1
      - feat11_1
      - feat1_2
      - feat2_2
      - feat3_2
      - feat4_2
      - feat5_2
      - feat6_2
      - feat7_2
      - feat8_2
      - feat9_2
      - feat10_2
      - feat11_2
      - feat1_3
      - feat2_3
      - feat3_3
      - feat4_3
      - feat5_3
      - feat6_3
      - feat7_3
      - feat8_3
      - feat9_3
      - feat10_3
      - feat11_3
      mappings:
        feat1: feat1
        feat10: feat10
        feat10_1: feat10_1
        feat10_2: feat10_2
        feat10_3: feat10_3
        feat11: feat11
        feat11_1: feat11_1
        feat11_2: feat11_2
        feat11_3: feat11_3
        feat1_1: feat1_1
        feat1_2: feat1_2
        feat1_3: feat1_3
        feat2: feat2
        feat2_1: feat2_1
        feat2_2: feat2_2
        feat2_3: feat2_3
        feat3: feat3
        feat3_1: feat3_1
        feat3_2: feat3_2
        feat3_3: feat3_3
        feat4: feat4
        feat4_1: feat4_1
        feat4_2: feat4_2
        feat4_3: feat4_3
        feat5: feat5
        feat5_1: feat5_1
        feat5_2: feat5_2
        feat5_3: feat5_3
        feat6: feat6
        feat6_1: feat6_1
        feat6_2: feat6_2
        feat6_3: feat6_3
        feat7: feat7
        feat7_1: feat7_1
        feat7_2: feat7_2
        feat7_3: feat7_3
        feat8: feat8
        feat8_1: feat8_1
        feat8_2: feat8_2
        feat8_3: feat8_3
        feat9: feat9
        feat9_1: feat9_1
        feat9_2: feat9_2
        feat9_3: feat9_3
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  parents:
  - f0195a31-88d5-4ff8-f8c6-08dc15ea238c
  transform_class: FillMissingValue
- id: 541db317-589a-44a3-f8c8-08dc15ea238c
  init_kwargs: {}
  inputs:
    f0195a31-88d5-4ff8-f8c6-08dc15ea238c:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat1_1
      - feat2_1
      - feat3_1
      - feat4_1
      - feat5_1
      - feat6_1
      - feat7_1
      - feat8_1
      - feat9_1
      - feat10_1
      - feat11_1
      - feat1_2
      - feat2_2
      - feat3_2
      - feat4_2
      - feat5_2
      - feat6_2
      - feat7_2
      - feat8_2
      - feat9_2
      - feat10_2
      - feat11_2
      - feat1_3
      - feat2_3
      - feat3_3
      - feat4_3
      - feat5_3
      - feat6_3
      - feat7_3
      - feat8_3
      - feat9_3
      - feat10_3
      - feat11_3
      mappings:
        feat1: feat1
        feat10: feat10
        feat10_1: feat10_1
        feat10_2: feat10_2
        feat10_3: feat10_3
        feat11: feat11
        feat11_1: feat11_1
        feat11_2: feat11_2
        feat11_3: feat11_3
        feat1_1: feat1_1
        feat1_2: feat1_2
        feat1_3: feat1_3
        feat2: feat2
        feat2_1: feat2_1
        feat2_2: feat2_2
        feat2_3: feat2_3
        feat3: feat3
        feat3_1: feat3_1
        feat3_2: feat3_2
        feat3_3: feat3_3
        feat4: feat4
        feat4_1: feat4_1
        feat4_2: feat4_2
        feat4_3: feat4_3
        feat5: feat5
        feat5_1: feat5_1
        feat5_2: feat5_2
        feat5_3: feat5_3
        feat6: feat6
        feat6_1: feat6_1
        feat6_2: feat6_2
        feat6_3: feat6_3
        feat7: feat7
        feat7_1: feat7_1
        feat7_2: feat7_2
        feat7_3: feat7_3
        feat8: feat8
        feat8_1: feat8_1
        feat8_2: feat8_2
        feat8_3: feat8_3
        feat9: feat9
        feat9_1: feat9_1
        feat9_2: feat9_2
        feat9_3: feat9_3
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  parents:
  - f0195a31-88d5-4ff8-f8c6-08dc15ea238c
  transform_class: FillMissingValue
- id: output
  init_kwargs: {}
  inputs:
    541db317-589a-44a3-f8c8-08dc15ea238c:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat1_1
      - feat2_1
      - feat3_1
      - feat4_1
      - feat5_1
      - feat6_1
      - feat7_1
      - feat8_1
      - feat9_1
      - feat10_1
      - feat11_1
      - feat1_2
      - feat2_2
      - feat3_2
      - feat4_2
      - feat5_2
      - feat6_2
      - feat7_2
      - feat8_2
      - feat9_2
      - feat10_2
      - feat11_2
      - feat1_3
      - feat2_3
      - feat3_3
      - feat4_3
      - feat5_3
      - feat6_3
      - feat7_3
      - feat8_3
      - feat9_3
      - feat10_3
      - feat11_3
      mappings:
        feat1: feat1
        feat10: feat10
        feat10_1: feat10_1
        feat10_2: feat10_2
        feat10_3: feat10_3
        feat11: feat11
        feat11_1: feat11_1
        feat11_2: feat11_2
        feat11_3: feat11_3
        feat1_1: feat1_1
        feat1_2: feat1_2
        feat1_3: feat1_3
        feat2: feat2
        feat2_1: feat2_1
        feat2_2: feat2_2
        feat2_3: feat2_3
        feat3: feat3
        feat3_1: feat3_1
        feat3_2: feat3_2
        feat3_3: feat3_3
        feat4: feat4
        feat4_1: feat4_1
        feat4_2: feat4_2
        feat4_3: feat4_3
        feat5: feat5
        feat5_1: feat5_1
        feat5_2: feat5_2
        feat5_3: feat5_3
        feat6: feat6
        feat6_1: feat6_1
        feat6_2: feat6_2
        feat6_3: feat6_3
        feat7: feat7
        feat7_1: feat7_1
        feat7_2: feat7_2
        feat7_3: feat7_3
        feat8: feat8
        feat8_1: feat8_1
        feat8_2: feat8_2
        feat8_3: feat8_3
        feat9: feat9
        feat9_1: feat9_1
        feat9_2: feat9_2
        feat9_3: feat9_3
    e0fe7e13-1286-4df6-f8c5-08dc15ea238c:
      columns:
      - feat12_22
      - feat12_22_22
      mappings:
        feat12_22: feat12_22
        feat12_22_22: feat12_22_22
  outputs:
  - feat12_22_22
  - feat12_22
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  parents:
  - e0fe7e13-1286-4df6-f8c5-08dc15ea238c
  - 541db317-589a-44a3-f8c8-08dc15ea238c
  transform_class: DefaultTransformer
- id: output
  init_kwargs: {}
  inputs:
    541db317-589a-44a3-f8c8-08dc15ea238c:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat1_1
      - feat2_1
      - feat3_1
      - feat4_1
      - feat5_1
      - feat6_1
      - feat7_1
      - feat8_1
      - feat9_1
      - feat10_1
      - feat11_1
      - feat1_2
      - feat2_2
      - feat3_2
      - feat4_2
      - feat5_2
      - feat6_2
      - feat7_2
      - feat8_2
      - feat9_2
      - feat10_2
      - feat11_2
      - feat1_3
      - feat2_3
      - feat3_3
      - feat4_3
      - feat5_3
      - feat6_3
      - feat7_3
      - feat8_3
      - feat9_3
      - feat10_3
      - feat11_3
      mappings:
        feat1: feat1
        feat10: feat10
        feat10_1: feat10_1
        feat10_2: feat10_2
        feat10_3: feat10_3
        feat11: feat11
        feat11_1: feat11_1
        feat11_2: feat11_2
        feat11_3: feat11_3
        feat1_1: feat1_1
        feat1_2: feat1_2
        feat1_3: feat1_3
        feat2: feat2
        feat2_1: feat2_1
        feat2_2: feat2_2
        feat2_3: feat2_3
        feat3: feat3
        feat3_1: feat3_1
        feat3_2: feat3_2
        feat3_3: feat3_3
        feat4: feat4
        feat4_1: feat4_1
        feat4_2: feat4_2
        feat4_3: feat4_3
        feat5: feat5
        feat5_1: feat5_1
        feat5_2: feat5_2
        feat5_3: feat5_3
        feat6: feat6
        feat6_1: feat6_1
        feat6_2: feat6_2
        feat6_3: feat6_3
        feat7: feat7
        feat7_1: feat7_1
        feat7_2: feat7_2
        feat7_3: feat7_3
        feat8: feat8
        feat8_1: feat8_1
        feat8_2: feat8_2
        feat8_3: feat8_3
        feat9: feat9
        feat9_1: feat9_1
        feat9_2: feat9_2
        feat9_3: feat9_3
    e0fe7e13-1286-4df6-f8c5-08dc15ea238c:
      columns:
      - feat12_22
      - feat12_22_22
      mappings:
        feat12_22: feat12_22
        feat12_22_22: feat12_22_22
  outputs:
  - feat12_22_22
  - feat12_22
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  parents:
  - e0fe7e13-1286-4df6-f8c5-08dc15ea238c
  - 541db317-589a-44a3-f8c8-08dc15ea238c
  transform_class: DefaultTransformer
