graph:
- metadata:
    data_key: ''
    data_unit: second
    max_historical_days: 3
  topo_ids:
  - input
  - 02d2b3d4-a0fb-40c2-3be3-08dc1328c977
  - 2431741a-400f-4344-3be2-08dc1328c977
  - 844cf13c-0d57-4685-3be1-08dc1328c977
  - f0b848ca-4570-4b64-3be4-08dc1328c977
  - output
  type: timeseries
nodes:
- id: 02d2b3d4-a0fb-40c2-3be3-08dc1328c977
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      mappings:
        Timestamp: Timestamp
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat12: feat12
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - Timestamp
  - feat12
  parents:
  - input
  transform_class: TargetPass
- id: 02d2b3d4-a0fb-40c2-3be3-08dc1328c977
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      mappings:
        Timestamp: Timestamp
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat12: feat12
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - Timestamp
  - feat12
  parents:
  - input
  transform_class: TargetPass
- id: 2431741a-400f-4344-3be2-08dc1328c977
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      mappings:
        Timestamp: Timestamp
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat12: feat12
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - Timestamp
  - feat12
  parents:
  - input
  transform_class: MinMaxTransform
- id: 2431741a-400f-4344-3be2-08dc1328c977
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      mappings:
        Timestamp: Timestamp
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat12: feat12
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - Timestamp
  - feat12
  parents:
  - input
  transform_class: MinMaxTransform
- id: 844cf13c-0d57-4685-3be1-08dc1328c977
  init_kwargs: {}
  inputs:
    2431741a-400f-4344-3be2-08dc1328c977:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      mappings:
        Timestamp: Timestamp
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat12: feat12
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - Timestamp
  - feat12
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - Timestamp_1
  - feat12_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - Timestamp_2
  - feat12_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  - Timestamp_3
  - feat12_3
  parents:
  - 2431741a-400f-4344-3be2-08dc1328c977
  transform_class: LagFeature
- id: 844cf13c-0d57-4685-3be1-08dc1328c977
  init_kwargs: {}
  inputs:
    2431741a-400f-4344-3be2-08dc1328c977:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      mappings:
        Timestamp: Timestamp
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat12: feat12
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - Timestamp
  - feat12
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - Timestamp_1
  - feat12_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - Timestamp_2
  - feat12_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  - Timestamp_3
  - feat12_3
  parents:
  - 2431741a-400f-4344-3be2-08dc1328c977
  transform_class: LagFeature
- id: f0b848ca-4570-4b64-3be4-08dc1328c977
  init_kwargs: {}
  inputs:
    844cf13c-0d57-4685-3be1-08dc1328c977:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      - feat1_1
      - feat2_1
      - feat3_1
      - feat4_1
      - feat5_1
      - feat6_1
      - feat7_1
      - feat8_1
      - feat9_1
      - feat10_1
      - feat11_1
      - feat12_1
      - Timestamp_1
      - feat1_2
      - feat2_2
      - feat3_2
      - feat4_2
      - feat5_2
      - feat6_2
      - feat7_2
      - feat8_2
      - feat9_2
      - feat10_2
      - feat11_2
      - feat12_2
      - Timestamp_2
      - feat1_3
      - feat2_3
      - feat3_3
      - feat4_3
      - feat5_3
      - feat6_3
      - feat7_3
      - feat8_3
      - feat9_3
      - feat10_3
      - feat11_3
      - feat12_3
      - Timestamp_3
      mappings:
        Timestamp: Timestamp
        Timestamp_1: Timestamp_1
        Timestamp_2: Timestamp_2
        Timestamp_3: Timestamp_3
        feat1: feat1
        feat10: feat10
        feat10_1: feat10_1
        feat10_2: feat10_2
        feat10_3: feat10_3
        feat11: feat11
        feat11_1: feat11_1
        feat11_2: feat11_2
        feat11_3: feat11_3
        feat12: feat12
        feat12_1: feat12_1
        feat12_2: feat12_2
        feat12_3: feat12_3
        feat1_1: feat1_1
        feat1_2: feat1_2
        feat1_3: feat1_3
        feat2: feat2
        feat2_1: feat2_1
        feat2_2: feat2_2
        feat2_3: feat2_3
        feat3: feat3
        feat3_1: feat3_1
        feat3_2: feat3_2
        feat3_3: feat3_3
        feat4: feat4
        feat4_1: feat4_1
        feat4_2: feat4_2
        feat4_3: feat4_3
        feat5: feat5
        feat5_1: feat5_1
        feat5_2: feat5_2
        feat5_3: feat5_3
        feat6: feat6
        feat6_1: feat6_1
        feat6_2: feat6_2
        feat6_3: feat6_3
        feat7: feat7
        feat7_1: feat7_1
        feat7_2: feat7_2
        feat7_3: feat7_3
        feat8: feat8
        feat8_1: feat8_1
        feat8_2: feat8_2
        feat8_3: feat8_3
        feat9: feat9
        feat9_1: feat9_1
        feat9_2: feat9_2
        feat9_3: feat9_3
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - Timestamp
  - feat12
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - Timestamp_1
  - feat12_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - Timestamp_2
  - feat12_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  - Timestamp_3
  - feat12_3
  parents:
  - 844cf13c-0d57-4685-3be1-08dc1328c977
  transform_class: FillMissingValue
- id: f0b848ca-4570-4b64-3be4-08dc1328c977
  init_kwargs: {}
  inputs:
    844cf13c-0d57-4685-3be1-08dc1328c977:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      - feat1_1
      - feat2_1
      - feat3_1
      - feat4_1
      - feat5_1
      - feat6_1
      - feat7_1
      - feat8_1
      - feat9_1
      - feat10_1
      - feat11_1
      - feat12_1
      - Timestamp_1
      - feat1_2
      - feat2_2
      - feat3_2
      - feat4_2
      - feat5_2
      - feat6_2
      - feat7_2
      - feat8_2
      - feat9_2
      - feat10_2
      - feat11_2
      - feat12_2
      - Timestamp_2
      - feat1_3
      - feat2_3
      - feat3_3
      - feat4_3
      - feat5_3
      - feat6_3
      - feat7_3
      - feat8_3
      - feat9_3
      - feat10_3
      - feat11_3
      - feat12_3
      - Timestamp_3
      mappings:
        Timestamp: Timestamp
        Timestamp_1: Timestamp_1
        Timestamp_2: Timestamp_2
        Timestamp_3: Timestamp_3
        feat1: feat1
        feat10: feat10
        feat10_1: feat10_1
        feat10_2: feat10_2
        feat10_3: feat10_3
        feat11: feat11
        feat11_1: feat11_1
        feat11_2: feat11_2
        feat11_3: feat11_3
        feat12: feat12
        feat12_1: feat12_1
        feat12_2: feat12_2
        feat12_3: feat12_3
        feat1_1: feat1_1
        feat1_2: feat1_2
        feat1_3: feat1_3
        feat2: feat2
        feat2_1: feat2_1
        feat2_2: feat2_2
        feat2_3: feat2_3
        feat3: feat3
        feat3_1: feat3_1
        feat3_2: feat3_2
        feat3_3: feat3_3
        feat4: feat4
        feat4_1: feat4_1
        feat4_2: feat4_2
        feat4_3: feat4_3
        feat5: feat5
        feat5_1: feat5_1
        feat5_2: feat5_2
        feat5_3: feat5_3
        feat6: feat6
        feat6_1: feat6_1
        feat6_2: feat6_2
        feat6_3: feat6_3
        feat7: feat7
        feat7_1: feat7_1
        feat7_2: feat7_2
        feat7_3: feat7_3
        feat8: feat8
        feat8_1: feat8_1
        feat8_2: feat8_2
        feat8_3: feat8_3
        feat9: feat9
        feat9_1: feat9_1
        feat9_2: feat9_2
        feat9_3: feat9_3
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - Timestamp
  - feat12
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - Timestamp_1
  - feat12_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - Timestamp_2
  - feat12_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  - Timestamp_3
  - feat12_3
  parents:
  - 844cf13c-0d57-4685-3be1-08dc1328c977
  transform_class: FillMissingValue
- id: output
  init_kwargs: {}
  inputs:
    02d2b3d4-a0fb-40c2-3be3-08dc1328c977:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      mappings:
        Timestamp: Timestamp
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat12: feat12
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
    f0b848ca-4570-4b64-3be4-08dc1328c977:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      - feat1_1
      - feat2_1
      - feat3_1
      - feat4_1
      - feat5_1
      - feat6_1
      - feat7_1
      - feat8_1
      - feat9_1
      - feat10_1
      - feat11_1
      - Timestamp_1
      - feat1_2
      - feat2_2
      - feat3_2
      - feat4_2
      - feat5_2
      - feat6_2
      - feat7_2
      - feat8_2
      - feat9_2
      - feat10_2
      - feat11_2
      - Timestamp_2
      - feat1_3
      - feat2_3
      - feat3_3
      - feat4_3
      - feat5_3
      - feat6_3
      - feat7_3
      - feat8_3
      - feat9_3
      - feat10_3
      - feat11_3
      - Timestamp_3
      - feat12_3
      - feat12_2
      - feat12_1
      mappings:
        Timestamp: Timestamp_1
        Timestamp_1: Timestamp_1
        Timestamp_2: Timestamp_2
        Timestamp_3: Timestamp_3
        feat1: feat1_1
        feat10: feat10_1
        feat10_1: feat10_1
        feat10_2: feat10_2
        feat10_3: feat10_3
        feat11: feat11_1
        feat11_1: feat11_1
        feat11_2: feat11_2
        feat11_3: feat11_3
        feat12: feat12_1
        feat12_1: feat12_1
        feat12_2: feat12_2
        feat12_3: feat12_3
        feat1_1: feat1_1
        feat1_2: feat1_2
        feat1_3: feat1_3
        feat2: feat2_1
        feat2_1: feat2_1
        feat2_2: feat2_2
        feat2_3: feat2_3
        feat3: feat3_1
        feat3_1: feat3_1
        feat3_2: feat3_2
        feat3_3: feat3_3
        feat4: feat4_1
        feat4_1: feat4_1
        feat4_2: feat4_2
        feat4_3: feat4_3
        feat5: feat5_1
        feat5_1: feat5_1
        feat5_2: feat5_2
        feat5_3: feat5_3
        feat6: feat6_1
        feat6_1: feat6_1
        feat6_2: feat6_2
        feat6_3: feat6_3
        feat7: feat7_1
        feat7_1: feat7_1
        feat7_2: feat7_2
        feat7_3: feat7_3
        feat8: feat8_1
        feat8_1: feat8_1
        feat8_2: feat8_2
        feat8_3: feat8_3
        feat9: feat9_1
        feat9_1: feat9_1
        feat9_2: feat9_2
        feat9_3: feat9_3
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - Timestamp
  - feat12
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - Timestamp_1
  - feat12_1
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - Timestamp_1
  - feat12_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - Timestamp_2
  - feat12_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  - Timestamp_3
  - feat12_3
  parents:
  - 02d2b3d4-a0fb-40c2-3be3-08dc1328c977
  - f0b848ca-4570-4b64-3be4-08dc1328c977
  transform_class: DefaultTransformer
- id: output
  init_kwargs: {}
  inputs:
    02d2b3d4-a0fb-40c2-3be3-08dc1328c977:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      mappings:
        Timestamp: Timestamp
        feat1: feat1
        feat10: feat10
        feat11: feat11
        feat12: feat12
        feat2: feat2
        feat3: feat3
        feat4: feat4
        feat5: feat5
        feat6: feat6
        feat7: feat7
        feat8: feat8
        feat9: feat9
    f0b848ca-4570-4b64-3be4-08dc1328c977:
      columns:
      - feat1
      - feat2
      - feat3
      - feat4
      - feat5
      - feat6
      - feat7
      - feat8
      - feat9
      - feat10
      - feat11
      - feat12
      - Timestamp
      - feat1_1
      - feat2_1
      - feat3_1
      - feat4_1
      - feat5_1
      - feat6_1
      - feat7_1
      - feat8_1
      - feat9_1
      - feat10_1
      - feat11_1
      - Timestamp_1
      - feat1_2
      - feat2_2
      - feat3_2
      - feat4_2
      - feat5_2
      - feat6_2
      - feat7_2
      - feat8_2
      - feat9_2
      - feat10_2
      - feat11_2
      - Timestamp_2
      - feat1_3
      - feat2_3
      - feat3_3
      - feat4_3
      - feat5_3
      - feat6_3
      - feat7_3
      - feat8_3
      - feat9_3
      - feat10_3
      - feat11_3
      - Timestamp_3
      - feat12_3
      - feat12_2
      - feat12_1
      mappings:
        Timestamp: Timestamp_1
        Timestamp_1: Timestamp_1
        Timestamp_2: Timestamp_2
        Timestamp_3: Timestamp_3
        feat1: feat1_1
        feat10: feat10_1
        feat10_1: feat10_1
        feat10_2: feat10_2
        feat10_3: feat10_3
        feat11: feat11_1
        feat11_1: feat11_1
        feat11_2: feat11_2
        feat11_3: feat11_3
        feat12: feat12_1
        feat12_1: feat12_1
        feat12_2: feat12_2
        feat12_3: feat12_3
        feat1_1: feat1_1
        feat1_2: feat1_2
        feat1_3: feat1_3
        feat2: feat2_1
        feat2_1: feat2_1
        feat2_2: feat2_2
        feat2_3: feat2_3
        feat3: feat3_1
        feat3_1: feat3_1
        feat3_2: feat3_2
        feat3_3: feat3_3
        feat4: feat4_1
        feat4_1: feat4_1
        feat4_2: feat4_2
        feat4_3: feat4_3
        feat5: feat5_1
        feat5_1: feat5_1
        feat5_2: feat5_2
        feat5_3: feat5_3
        feat6: feat6_1
        feat6_1: feat6_1
        feat6_2: feat6_2
        feat6_3: feat6_3
        feat7: feat7_1
        feat7_1: feat7_1
        feat7_2: feat7_2
        feat7_3: feat7_3
        feat8: feat8_1
        feat8_1: feat8_1
        feat8_2: feat8_2
        feat8_3: feat8_3
        feat9: feat9_1
        feat9_1: feat9_1
        feat9_2: feat9_2
        feat9_3: feat9_3
  outputs:
  - feat1
  - feat2
  - feat3
  - feat4
  - feat5
  - feat6
  - feat7
  - feat8
  - feat9
  - feat10
  - feat11
  - Timestamp
  - feat12
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - Timestamp_1
  - feat12_1
  - feat1_1
  - feat2_1
  - feat3_1
  - feat4_1
  - feat5_1
  - feat6_1
  - feat7_1
  - feat8_1
  - feat9_1
  - feat10_1
  - feat11_1
  - Timestamp_1
  - feat12_1
  - feat1_2
  - feat2_2
  - feat3_2
  - feat4_2
  - feat5_2
  - feat6_2
  - feat7_2
  - feat8_2
  - feat9_2
  - feat10_2
  - feat11_2
  - Timestamp_2
  - feat12_2
  - feat1_3
  - feat2_3
  - feat3_3
  - feat4_3
  - feat5_3
  - feat6_3
  - feat7_3
  - feat8_3
  - feat9_3
  - feat10_3
  - feat11_3
  - Timestamp_3
  - feat12_3
  parents:
  - 02d2b3d4-a0fb-40c2-3be3-08dc1328c977
  - f0b848ca-4570-4b64-3be4-08dc1328c977
  transform_class: DefaultTransformer
