graph:
- metadata:
    data_key: ''
    data_unit: second
    max_historical_periods: 0
  mode: backward
  topo_ids:
  - 73b249b6-7f9a-4566-f8b4-08dc15ea238c
  - 3b2c5bf4-7aca-4755-f8b7-08dc15ea238c
  - 011b4e1e-fe93-428c-f8b3-08dc15ea238c
  - output
  type: normal
nodes:
- id: 73b249b6-7f9a-4566-f8b4-08dc15ea238c
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat12
      mappings:
        feat12: feat12
  outputs:
  - feat12
  parents:
  - input
  transform_class: TargetPass
- id: 73b249b6-7f9a-4566-f8b4-08dc15ea238c
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat12
      mappings:
        feat12: feat12
  outputs:
  - feat12
  parents:
  - input
  transform_class: TargetPass
- id: 3b2c5bf4-7aca-4755-f8b7-08dc15ea238c
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat12
      mappings:
        feat12: feat12_22
  outputs:
  - feat12_22
  parents:
  - input
  transform_class: TargetPass
- id: 3b2c5bf4-7aca-4755-f8b7-08dc15ea238c
  init_kwargs: {}
  inputs:
    input:
      columns:
      - feat12
      mappings:
        feat12: feat12_22
  outputs:
  - feat12_22
  parents:
  - input
  transform_class: TargetPass
